### ISSUE TITLE
Patterns aren't documented

### ISSUE THREAD

**Issue by brauliobz** [rust-lang-nursery/reference#83]
As a guide, it may have these sections:

- [x] Patterns (introduction)
- [x] Wildcard pattern `_`
- [ ] Reference patterns `& ...`
- [ ] Tuple patterns `(a, b, ...)`
- [x] Slice patterns `[a, b, ..i, y, z]]`
- [ ] Identifier patterns `binding @ subpattern`
- [x] Literal patterns `1`, `2`, etc
- [x] Range patterns `0..10`
- [ ] Struct patterns `Variant {a, b, ...}`
- [ ] Tuple struct patterns `Variant (a, b, ...)`
- [ ] Box pattern
- [x] Refutability
- [x] Destructuring

**Comment by matthewjasper** [comment]
Thanks for this!

For anyone wanting to work on this: there is currently some (not enough IMO) information on patterns in the expressions chapter under `match` that could be moved to its own page as a starting point. The second edition of the book also has a whole chapter on patterns.

Some of these are currently unstable so should be in the unstable book if they aren't already.
Your list could also have enum variant patterns, `ref`, `@` and refutability.

**Comment by brauliobz** [comment]
Thank you for taking a look.

The enum patterns are called TupleStruct patterns [in the parser](https://github.com/rust-lang/rust/blob/287de2595a40c03d9ffe81f55c13c731fd01583f/src/libsyntax/ast.rs#L543).

I included some examples, since the names aren't all very descriptive.

**Comment by brauliobz** [comment]
I'm working on this.
Current progress can be seen [here](https://brauliobz.github.io/rust-reference/patterns.html).

**Comment by alercah** [comment]
RFC 1445 should be incorporated: https://github.com/nikomatsakis/rfcs/blob/restrict-constants-in-patterns/text/0000-restrict-constants-in-patterns.md

@brauliobz, have you abandoned work on this?

**Comment by brauliobz** [comment]
@alercah Yeah, for while... I'm trying to get back to it, though.
