### ISSUE TITLE
Document the (complete) grammar inside the specification

### ISSUE THREAD

**Issue by brauliobz** [rust-lang-nursery/reference#84]
This issue tracks the work in documenting the grammar.

Since [the grammar](https://github.com/rust-lang/rust/blob/master/src/doc/grammar.md) is *very* incomplete and I'm willing to complete it, I thought it would be better to do this inside the reference, alongside each item of the language.

Progress:

- [x] Create a script to join the scattered grammar in one place.
- [x] Lexical productions
  - [x] Keywords PR #97
  - [x] Identifiers PR #89 
  - [x] Comments PR #85
  - [x] Literals
    - [x] Char PR #121
    - [x] String PR #121
    - [x] Raw string PR #121
    - [x] Byte PR #121
    - [x] Byte string PR #121
    - [x] Raw byte string PR #121
    - [x] Integer PR #108
    - [x] Float PR #109 
    - [x] Bools PR #110 
  - [x] Symbols _draft_
  - [x] Paths _draft_
- [x] Syntax productions
  - [x] Crates PR #87
  - [x] Items
    - [x] Visibility PR #90
    - [x] Modules PR #143 
    - [x] Extern crate PR #144 
    - [x] Use declaration PR #145 
    - [x] Static item
    - [x] Const value
    - [x] Functions _draft_
    - [x] Type aliases
    - [x] Enums
    - [x] Structs
    - [x] Unions
    - [x] Extern blocks
    - [x] Traits _draft_
    - [x] Implementations _draft_
    - [x] Const functions
    - [x] Extern functions
  - [x] Attributes PR #88
  - [x] Statements
    - [x] Item declarations
    - [x] `let` statements 
    - [x] Expression statements
  - [x] Expressions _draft_
    - [x] Literal #138 
    - [x] Path
    - [x] Tuple
    - [x] Struct
    - [x] EnumerationVariant
    - [x] Block #136 
    - [x] Method call
    - [x] Field access #158 
    - [x] Tuple indexing
    - [x] Call expression #134 
    - [x] Closure #135 
    - [x] Array expression #133 
    - [x] Indexing expression #133 
    - [x] Range expression #142 
    - [x] Operator expression #141 
      - [x] borrow
      - [x] dereference
      - [x] error propagation
      - [x] negation
      - [x] arithmetic and logical
      - [x] comparison
      - [x] lazy boolean
      - [x] typecast
      - [x] assignment
      - [x] compound assignment
    - [x] Grouped expression #141 
    - [x] Loop expressions #139 
      - [x] loop
      - [x] while
      - [x] while let
      - [x] for
      - [x] break
      - [x] continue
    - [x] if #137 
    - [x] If let #137 
    - [x] match
    - [x] return #140 
  - [x] Patterns _draft_
    - [x] Wildcard
    - [x] Reference
    - [x] Struct
    - [x] TupleStruct
    - [x] Tuple
    - [x] Slice
    - [x] Identifier
    - [x] Path
    - [x] Literal
    - [x] Range
    - [x] Box
  - [x] Types
    - [x] path type
    - [x] qualified path type
    - [x] tuple type
    - [x] array type
    - [x] slice type
    - [x] reference type
    - [x] inferred type
    - [x] raw pointer type
    - [x] function pointer type
    - [x] trait object type
    - [x] impl trait type
    - [x] never type (divergent functions)
    - [x] parenthesized type
  - [x] Macros
    - [x] Macro definitions
    - [x] Macro invocations (and the places they can appear, scattered in other grammar items)

**Comment by brauliobz** [comment]
[Rendered here.](https://brauliobz.github.io/rust-reference/index.html)

**Comment by brauliobz** [comment]
Grammar in one place [rendered here](https://brauliobz.github.io/rust-reference/grammar.html#infinite-loops).

Still some cleanup to do: links and references must be removed and, if not difficult, should be internal to the grammar.md page.

**Comment by ehuss** [comment]
If nobody minds, I'd like to try to continue this project.  There are some chapters that I think could use some clarification and examples, so unless anyone objects I might make some changes to the text at the same time.

**Comment by ehuss** [comment]
I'm going to close this. Everything should be documented now. If there is anything missing or incorrect, new issues should be filed.  Many thanks to @brauliobz for all the work put into this.
